<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TimeOps.Application\TimeOps.Application.csproj" />
    <ProjectReference Include="..\TimeOps.Infrastructure\TimeOps.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>TimeOps-local</UserSecretsId>
  </PropertyGroup>

</Project>
